#! /usr/bin/env python3

import json
import shlex
import subprocess as sp
from pathlib import Path
from typing import List

import typer
from rich import print as echo


app = typer.Typer(pretty_exceptions_show_locals=False)


@app.command()
def main(
    files: List[Path],
    outfile: Path = "joined.pdf",
    outfile_prefix: str = "plot_",
    outfile_suffix: str = "pdf",
    splice: int = 50,
    pointsize: int = 20,
):
    _outfiles = []
    for ii, file in enumerate(files):
        tag = str(file)

        echo("... Tag:")
        echo(tag)

        if not file.exists():
            echo(f"... {file} not found, skip")
            continue

        _outfile = f"{outfile_prefix}{ii:03d}.{outfile_suffix}"

        cmd = f"convert {file} "
        cmd += "-gravity South "
        cmd += f"-pointsize {pointsize} "
        cmd += f"-splice 0x{splice:d} "
        cmd += f"-annotate +0+20 '{tag}' "
        cmd += f"{_outfile}"

        echo("... run:")
        echo(cmd)

        sp.run(shlex.split(cmd))
        _outfiles.append(_outfile)

    _cmd = "pdfjam "
    for _outfile in _outfiles:
        _cmd += f"{_outfile} '-' "
    _cmd += "--no-tidy "
    _cmd += "--landscape "
    _cmd += f"--outfile {outfile}"

    # check if files actually exist
    for _file in _outfiles:
        assert Path(_file).exists(), f"{_file} does not exist, arguments are folders!"

    echo("... run:")
    echo(_cmd)
    sp.run(shlex.split(_cmd), check=True)

    # cleanup
    for _file in _outfiles:
        Path(_file).unlink()

    echo("done.")


if __name__ == "__main__":
    app()
