#! /usr/bin/env python3

import os
import shutil
from pathlib import Path

import numpy as np
import typer
from ase.io import read
from ase.io.espresso import write_espresso_in
from rich import print as echo
from typing import Tuple

app = typer.Typer()


def get_input_data(control: dict, system: dict, electrons: dict):
    return {"control": control, "system": system, "electrons": electrons}


@app.command()
def main(
    file: str,
    outfile: str = "pw.in.scf",
    ecutwfc: float = 50.0,
    xc: str = "pbe",
    kpts: Tuple[int, int, int] = [None, None, None],
    kpts_density: float = 5.0,
    tprnfor: bool = True,
    tstress: bool = True,
    conv_thr: float = 1e-12,
    diagonalization: str = "david",
    diago_full_acc: bool = True,
    prefix: str = "qe",
    outdir: str = "./",
    wfcdir: str = None,
    pseudodir: str = "./pseudopotentials",
    format="aims",
):
    """Convert geometry file into pw.in template"""
    atoms = read(file, format=format)

    echo(atoms)

    if None in kpts:
        r_lattice = np.linalg.norm(2.0 * np.pi * atoms.cell.reciprocal(), axis=1)
        kgrid = tuple(np.ceil(r_lattice * kpts_density).astype(int))
        echo(f".. kpoints density: {kpts_density} --> {kgrid}")
    else:
        kgrid = kpts

    path_pseudo = Path(os.environ["ESPRESSO_PSEUDO"])

    # copy pseudopoentials in folder and add to dict
    _folder = Path(pseudodir)
    _folder.mkdir(exist_ok=True)
    pseudopotentials = {}
    for elem in np.unique(atoms.symbols):
        file = next(path_pseudo.glob(f"{elem}_*PBE-1.2.upf"))
        # copy
        _newfile = _folder / file.name
        echo(f".. copy {file} to {_folder}")
        shutil.copy(file, _newfile)
        pseudopotentials[elem] = file.name

    # default control
    data_control = {
        "calculation": "scf",
        "prefix": prefix,
        "outdir": outdir,
        "pseudo_dir": pseudodir,
        "tprnfor": tprnfor,
        "tstress": tstress,
    }
    if wfcdir is not None:
        data_control["wfcdir"] = wfcdir

    # default electrons
    data_electrons = {
        "conv_thr": conv_thr,
        "diagonalization": diagonalization,
        "diago_full_acc": diago_full_acc,
    }
    # system
    data_system = {
        "ecutwfc": ecutwfc,
        "input_dft": xc,
    }

    # report
    echo("Will set up following things:")
    echo("Control:")
    echo(data_control)
    echo("System:")
    echo(data_system)
    echo("Electrons:")
    echo(data_electrons)

    # scf
    echo(f".. write {outfile}")
    with open(outfile, "w") as f:
        input_data = get_input_data(data_control, data_system, data_electrons)
        write_espresso_in(
            f,
            atoms=atoms,
            kpts=kgrid,
            pseudopotentials=pseudopotentials,
            input_data=input_data,
        )


if __name__ == "__main__":
    app()
